services:
  audo-eq-api:
    volumes: []
    command:
      - uvicorn
      - audo_eq.api:app
      - --host
      - ${API_HOST:-0.0.0.0}
      - --port
      - "${API_PORT:-8000}"
      - --workers
      - "${UVICORN_WORKERS:-1}"
      - --log-level
      - "${UVICORN_LOG_LEVEL:-info}"
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: "1.00"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M
