services:
  audo-eq-api:
    volumes:
      - ./src:/app/src
    command:
      - uvicorn
      - audo_eq.api:app
      - --host
      - ${API_HOST:-0.0.0.0}
      - --port
      - "${API_PORT:-8000}"
      - --log-level
      - "${UVICORN_LOG_LEVEL:-info}"
      - --reload
